-- 1. Cleanup previous tests (Optional)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('DEMO_ORDER_ITEMS', 'DEMO_ORDERS', 'DEMO_CUSTOMERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- 2. Create tables
CREATE TABLE demo_customers (
    customer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(50),
    email           VARCHAR2(100),
    registration_dt DATE,
    segment         VARCHAR2(20) -- E.g., VIP, STANDARD
);

CREATE TABLE demo_orders (
    order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER,
    order_date      DATE,
    total_amount    NUMBER(10, 2),
    status          VARCHAR2(20),
    CONSTRAINT fk_cust FOREIGN KEY (customer_id) REFERENCES demo_customers(customer_id)
);

CREATE TABLE demo_order_items (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER,
    product_id      NUMBER,
    quantity        NUMBER,
    unit_price      NUMBER(10, 2),
    CONSTRAINT fk_ord FOREIGN KEY (order_id) REFERENCES demo_orders(order_id)
);

-- 3. Data population (PL/SQL using BULK INSERT for performance)
DECLARE
    TYPE t_cust IS TABLE OF demo_customers%ROWTYPE;
    v_cust t_cust := t_cust();
    v_start_time TIMESTAMP;
BEGIN
    v_start_time := SYSTIMESTAMP;
    DBMS_OUTPUT.PUT_LINE('Starting data generation...');

    -- A. Generating 100,000 Customers
    INSERT INTO demo_customers (first_name, last_name, email, registration_dt, segment)
    SELECT 
        DBMS_RANDOM.STRING('U', 5),
        DBMS_RANDOM.STRING('U', 8),
        DBMS_RANDOM.STRING('L', 10) || '@test.com',
        TO_DATE('2020-01-01', 'YYYY-MM-DD') + DBMS_RANDOM.VALUE(0, 1000),
        CASE WHEN MOD(LEVEL, 20) = 0 THEN 'VIP' ELSE 'STANDARD' END
    FROM dual CONNECT BY LEVEL <= 100000;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Customers generated.');

    -- B. Generating 500,000 Orders (Avg 5 per client)
    INSERT INTO demo_orders (customer_id, order_date, total_amount, status)
    SELECT 
        TRUNC(DBMS_RANDOM.VALUE(1, 100000)), -- Random customer
        TO_DATE('2022-01-01', 'YYYY-MM-DD') + DBMS_RANDOM.VALUE(0, 365),
        ROUND(DBMS_RANDOM.VALUE(50, 5000), 2),
        CASE MOD(ROUND(DBMS_RANDOM.VALUE(1, 10)), 3) 
            WHEN 0 THEN 'CLOSED' 
            WHEN 1 THEN 'PENDING' 
            ELSE 'SHIPPED' 
        END
    FROM dual CONNECT BY LEVEL <= 500000;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Orders generated.');

    -- C. Generating 1,500,000 Order Items
    INSERT INTO demo_order_items (order_id, product_id, quantity, unit_price)
    SELECT 
        TRUNC(DBMS_RANDOM.VALUE(1, 500000)), -- Random order
        TRUNC(DBMS_RANDOM.VALUE(1, 1000)),   -- Random product
        TRUNC(DBMS_RANDOM.VALUE(1, 10)),
        ROUND(DBMS_RANDOM.VALUE(10, 500), 2)
    FROM dual CONNECT BY LEVEL <= 1500000;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Order items generated. Duration: ' || (SYSTIMESTAMP - v_start_time));
    
    -- IMPORTANT: Gather statistics so CBO is aware of the data
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'DEMO_CUSTOMERS');
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'DEMO_ORDERS');
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'DEMO_ORDER_ITEMS');
END;
/